import { v4 as uuidv4 } from "uuid";
// import tshirt from "../images/Palm_Angels.jpg";
import tshirt from "./images/Palm_Angels.jpg";
import fullImage from "./images/Palm_Angels_Full.jpg";
import fullFrontImage from "./images/Palm_Angels_Full_Front.jpg";

export const data = [
  {
    id: uuidv4(),
    name: `Cropped Stay Groovy off white`,
    image: [fullFrontImage, fullImage],
    price: 10.9,
    wholesaleQty: 9,
    wholesalePrice: 1.21,
    size: ["xl", "xs", "m", "s", "l", "xxl"],
    freeShipping: true,
    addedToCart: false,
  },
  {
    id: uuidv4(),
    name: `Basic Cactus White T-shirt`,
    image: [tshirt, fullImage],
    price: 13.25,
    wholesaleQty: 3,
    wholesalePrice: 4.42,
    size: ["xl", "l", "s"],
    freeShipping: true,
    addedToCart: false,
  },
  {
    id: uuidv4(),
    name: `Skater Black Sweatshirt`,
    image: [tshirt, fullImage],
    price: 25.9,
    wholesaleQty: 12,
    wholesalePrice: 2.16,
    size: ["xl", "xs", "xxl"],
    freeShipping: true,
    addedToCart: false,
  },
  {
    id: uuidv4(),
    name: `Skater Black Sweatshirt`,
    image: [tshirt, fullImage],
    price: 25.9,
    wholesaleQty: 12,
    wholesalePrice: 2.16,
    size: ["xl", "xxl", "m"],
    freeShipping: true,
    addedToCart: false,
  },
  {
    id: uuidv4(),
    name: `Skater Black Sweatshirt`,
    image: [tshirt, fullImage],
    price: 25.9,
    wholesaleQty: 12,
    wholesalePrice: 2.16,
    size: ["xl", "l", "xs"],
    freeShipping: true,
    addedToCart: false,
  },
  {
    id: uuidv4(),
    name: `Skater Black Sweatshirt`,
    image: [tshirt, fullImage],
    price: 25.9,
    wholesaleQty: 12,
    wholesalePrice: 2.16,
    size: ["xl", "m", "xs"],
    freeShipping: true,
    addedToCart: false,
  },
  {
    id: uuidv4(),
    name: `Skater Black Sweatshirt`,
    image: [tshirt, fullImage],
    price: 25.9,
    wholesaleQty: 12,
    wholesalePrice: 2.16,
    size: ["xl", "l", "m"],
    freeShipping: true,
    addedToCart: false,
  },
  {
    id: uuidv4(),
    name: `Skater Black Sweatshirt`,
    image: [tshirt, fullImage],
    price: 25.9,
    wholesaleQty: 12,
    wholesalePrice: 2.16,
    size: ["xl", "s", "l"],
    freeShipping: true,
    addedToCart: false,
  },
];
